### ISSUE TITLE
Broken with CJK character.

### ISSUE THREAD

**Issue by leopku** [willnorris/newbase60#1]
```go
fmt.Println(newbase60.DecodeToInt("http://www.example.com/books/白鹿原"))

// -> output: -6819340780163825664
```

**Comment by willnorris** [comment]
So you're definitely correct in that we are not handling multibyte characters properly, which is something we should be able to fix pretty easily.  All unrecognized characters (including CJK) are simply decoded as 0.  The thing that we're doing wrong here is that we are decoding them as multiple zeros per character, rather than 1.  So:

``` go
newbase60.DecodeToInt("白")
// -> returns: 0

newbase60.DecodeToInt("*")
// -> returns: 0
```

which is correct.  And having CJK characters at the beginning is fine:

``` go
newbase60.DecodeToInt("a")
// -> returns: 35

newbase60.DecodeToInt("白a")
// -> returns: 35

newbase60.DecodeToInt("*a")
// -> returns: 35
``` 
The problem is having them at the end:

``` go
newbase60.DecodeToInt("a白")
// -> returns: 7560000

newbase60.DecodeToInt("a*")

// -> returns: 2100
```

Though your example makes me wondering how you are using this... an actual URL wouldn't decode as base60 in any kind of meaningful way.  You really shouldn't ever have CJK characters in a base60 encoded string... it's defined as only using ASCII.

**Comment by willnorris** [comment]
So this now returns 2034346977788280832, which is the same as:

```go
fmt.Println(newbase60.DecodeToInt("http://www.example.com/books/000"))
```

which is the expected behavior.

**Comment by leopku** [comment]
Big thanks for your quickly reply.
